POST https://fullstack-part3-i509.onrender.com/api/persons
Content-Type: application/json

{
    "name": "New Moeny",
    "number": "123-4567"
}

###
GET https://fullstack-part3-i509.onrender.com/api/persons

###
DELETE https://fullstack-part3-i509.onrender.com/api/persons/2
